### PR TITLE
Add newsletter signup to homepage

### PR DESCRIPTION
**Pull request by jwade1327**
**UPDATED**:
Screen Shot 2023-01-16 at 12 06 25 PM

Screen Shot 2023-01-15 at 8 55 32 PM
Screen Shot 2023-01-14 at 12 58 34 PM

### CODE REVIEW

**Comment by jwade1327** [comment]
[Add newsletter sign up on homepage for staging sites](https://trello.com/c/HA48EaJt/139-add-newsletter-sign-up-on-homepage-for-staging-sites)

**Comment by Shinsina** [comment]
@jwade1327 Are they okay/aware this is pulling the LabPulse form or does this need to be update to include a Dr. Bicuspid form instead?

**Comment by jwade1327** [comment]
@Shinsina I updated the description to a more generic one until they provide us with a finalized version.

**Comment by Shinsina** [comment]
@jwade1327 Am I missing something nothing appears to have changed here: https://github.com/parameter1/science-medicine-group-websites/blob/master/sites/drbicuspid.com/config/newsletter.js

**Review by Shinsina — APPROVED** [review]

**Pull request merged**
