### PR TITLE
"Single Opt In" registration flow

### PR DESCRIPTION
**Pull request by Shinsina**
Newly created unconfirmed user in Braze from this updated process (i.e. No Login Link was clicked): 
Screenshot from 2024-07-08 14-13-10
Screenshot from 2024-07-08 14-13-19

### CODE REVIEW

**Comment by Shinsina** [comment]
[Single Opt In Process](https://trello.com/c/kcOAgYzY/602-single-opt-in-process)

**Comment by jwade1327** [comment]
@Shinsina I'm not sure if it's just me, but I tested this yesterday afternoon and was able to find myself in Braze _ONLY_ for DrB. (I never clicked the confirmation link from my email and received a newsletter this morning). For the AM and AME sign-ins I was unable to find my email address in Braze.

**Comment by jwade1327** [comment]
@Shinsina Richele and I both can confirm that emails entered from AME are **_NOT_** getting into Braze. DrB and AM are successful with the new changes.

**Review by jwade1327 — CHANGES_REQUESTED** [review]
@Shinsina Richele and I both can confirm that emails entered from AME are NOT getting into Braze. DrB and AM are successful with the new changes.

**Comment by Shinsina** [comment]
> @Shinsina Richele and I both can confirm that emails entered from AME are NOT getting into Braze. DrB and AM are successful with the new changes.

I just tested this for AME and see no issue: 
image

**Comment by jwade1327** [comment]
@Shinsina If the user is entering their email on AME they should be 'Subscribed' signed up for the AMEU_Daily and AMEU_Unconfirmed_Emails

**Review by jwade1327 — APPROVED** [review]

**Pull request merged**
